### ISSUE TITLE
Can't replicate Tanks and Temples score

### ISSUE THREAD

**Issue by EugenioTL** [alibaba/cascade-stereo#5]
Hi, I am trying to replicate the score on Tanks and Temples benchmark but reaching lower performances. To compute SfM and image undistortion I am using the default COLMAP pipeline, and for post-processing I am using fusible as explained.
Have you used different hyperparameters i.e. max_h, max_w or gipuma ones?
Thank you.

**Comment by gxd1994** [comment]
Hi@EugenioTL, 
You can set a larger resolution for better results.
Some experimental details on tanks and temples benchmark are as follows:
1.use sparse results from YaoYao 
https://drive.google.com/open?id=1YArOJaX9WVLJh4757uE8AEREYkgszrCo
2.set max_h = max_w = 2048，both fusible and gipuma are optional

**Comment by EugenioTL** [comment]
Ok, I am trying starting from this sparse database.
What about the other hyperparameters? Are all of the them the default ones?
Thank you very much.

**Comment by kwea123** [comment]
Hi @EugenioTL do you have any progress? I use [my reimplementation](https://github.com/kwea123/CasMVSNet_pl), and get similar performance on dtu dataset as this repo, but I can't get acceptable results on tanks...

I checked the `test.py` here, it seems the interval_ratios is still `"4,2,1"`. However I find this setting not optimal for tanks, I needed to change them into `"0.4, 0.2, 0.1"` or something similar to get good results for "Family", "Francis" and "Horse". For the rest, no matter how I tune the `interval_ratio`, which I think is the most important parameter, I cannot get reasonable results; either they contain too much noise, or they don't contain enough points. It even has nothing to do with depth fusion since the depth prediction already looks bizarre. One of my assumptions is that maybe 48 planes for the coarsest level is not enough for tanks, which is outdoor? I recently read a [paper](https://arxiv.org/pdf/1911.12012v1.pdf) which shares a similar concept with this one, and they use 160 planes at the coarsest level. I'm training that model now.
@gxd1994 Did you encounter the problem I described above? Do you have any trick to solve it? Thanks.

**Comment by gxd1994** [comment]
Hi @kwea123 you can try:
 1.use sparse results from YaoYao
https://drive.google.com/open?id=1YArOJaX9WVLJh4757uE8AEREYkgszrCo
2.set max_h = max_w = 2048，both fusible and gipuma are optional
if you using 160 planes in stage1, you will get better results.

**Comment by kwea123** [comment]
@gxd1994 Thank you.
I finally spotted my mistake... I thought all images are of size (1920, 1080)... then after running your code I realized some scenes are of size (2048, 1080). I changed the scaling accordingly and now I can get good results. Thank you very much.

**Comment by fanshixiong** [comment]
@kwea123 can you share the testing parameters you are using? I still can't get acceptable results.  Thanks!
